### ISSUE TITLE
Doesnt seem to work

### ISSUE THREAD

**Issue by Bread-sauce** [tommyvange/ArrStalledHandler#3]
I have about 10 stalled downloads in sonarr but it does not appear to see them.

2024-11-23 07:42:00,906 [INFO] Checking stalled downloads in Sonarr...
2024-11-23 07:42:00,907 [DEBUG] Starting new HTTP connection (1): 192.168.1.2:8989
2024-11-23 07:42:00,909 [DEBUG] http://192.168.1.2:8989 "GET /api/v3/queue?includeEpisode=true HTTP/11" 200 None
2024-11-23 07:42:00,909 [DEBUG] Stalled downloads for Sonarr: {}
2024-11-23 07:42:00,909 [INFO] Script execution completed. Sleeping for 300 seconds...

**Comment by tommyvange** [comment]
> I have about 10 stalled downloads in sonarr but it does not appear to see them.
> 
> 
> 
> 2024-11-23 07:42:00,906 [INFO] Checking stalled downloads in Sonarr...
> 
> 2024-11-23 07:42:00,907 [DEBUG] Starting new HTTP connection (1): 192.168.1.2:8989
> 
> 2024-11-23 07:42:00,909 [DEBUG] http://192.168.1.2:8989 "GET /api/v3/queue?includeEpisode=true HTTP/11" 200 None
> 
> 2024-11-23 07:42:00,909 [DEBUG] Stalled downloads for Sonarr: {}
> 
> 2024-11-23 07:42:00,909 [INFO] Script execution completed. Sleeping for 300 seconds...
> 
> 

Can you send me a screenshot of your Sonarr activity page and also a screenshot of the information about one of the stalled activities (hover over the cloud)?

**Comment by Bread-sauce** [comment]
![image](https://github.com/user-attachments/assets/19f811e2-4d97-461c-89cc-cec6c7dacd86)

**Comment by Bread-sauce** [comment]
![image](https://github.com/user-attachments/assets/38bae3f8-9064-49de-87c7-371b54ec6f13)

**Comment by Bread-sauce** [comment]
http://192.168.1.2:8989/api/v3/queue?includeEpisode=true?apikey=MY_API_KEY 
This shows nothing but blank screen.

http://192.168.1.2:8989/api/v3/queue?apikey=MY_API_KEY 
this does not show all shows

http://192.168.1.2:8989/api/v3/queue/details?apikey=MY_API_KEY 
shows the following.

![image](https://github.com/user-attachments/assets/d8783cda-b0e1-42ae-86e3-86dc356399a6)

**Comment by Bread-sauce** [comment]
http://192.168.1.2:8989/api/v3/queue?apikey=MY_API_KEY&includeEpisode=true&pageSize=100
This shows the stalled. added pagesize=100

![image](https://github.com/user-attachments/assets/d9d3d61a-49bc-49fa-aff8-d49354970784)

**Comment by Bread-sauce** [comment]
I think what is happening is i am downloading a bunch and some are stuck at downloading metadata. And it is not showing the stalled ones on the first page. So increasing the page size would work. Would it be possible to also search for ones stuck at downloading metadata?

![image](https://github.com/user-attachments/assets/69ece5c3-0923-4b13-b9b1-d94be43f830e)

**Comment by tommyvange** [comment]
Good work, it is probably related to the page size. I will look into it to tomorrow.

I'll also look into the downloading metadata status.

**Comment by Bread-sauce** [comment]
Thank you!

**Comment by tommyvange** [comment]
The bug with pagination should be solved in release [1.0.1](https://github.com/tommyvange/ArrStalledHandler/releases/tag/1.0.1), please update the docker container and try again. 

If you @Bread-sauce could create a separate issue for requesting handling of the "Downloading Metadata" that would be great.

**Comment by tommyvange** [comment]
Would you mind @Bread-sauce reporting back if the issue is solved whenever you have the time to update and test?
