### ISSUE TITLE
requesting handling of the "Downloading Metadata"

### ISSUE THREAD

**Issue by Bread-sauce** [tommyvange/ArrStalledHandler#6]
Stuck downloads, downloading metadata
http://192.168.1.2:8989/api/v3/queue?apikey=MY_API_KEY&includeEpisode=true&pageSize=100
![image](https://github.com/user-attachments/assets/ddf29fc9-6bc7-42a2-bec9-acd58c98e5ac)
![image](https://github.com/user-attachments/assets/d4116562-95c8-4d19-a647-9f42ea24d810)

**Comment by tommyvange** [comment]
Would you mind @Bread-sauce reporting back if the enhancement works as expected whenever you have the time to update and test?

You need to add the environment variable `COUNT_DOWNLOADING_METADATA_AS_STALLED` set to `true` to enable this fuction.

**Comment by tommyvange** [comment]
For future reference: This request was discussed in more detail in issue #3.

**Comment by Bread-sauce** [comment]
Looks like it is working! thank you
![image](https://github.com/user-attachments/assets/ce9465f8-f936-44aa-9555-76413bb814c0)
![image](https://github.com/user-attachments/assets/05f4b51c-66e7-4a43-8820-6c5290fffafe)

**Comment by tommyvange** [comment]
> Looks like it is working! thank you
> 
> ![image](https://github.com/user-attachments/assets/ce9465f8-f936-44aa-9555-76413bb814c0)
> 
> ![image](https://github.com/user-attachments/assets/05f4b51c-66e7-4a43-8820-6c5290fffafe)
> 
> 

Fantastic! Thank for the assist in debugging, and really detailed responses.
